[package]
name = "nightshift"
version = "0.0.2"
authors = ["smudge <nathan@ngriffith.com>"]
edition = "2018"
categories = ["command-line-utilities", "os::macos-apis"]
description = "A CLI for configuring 'Night Shift' on macOS 🌕🌖🌗🌘🌑"
repository = "https://github.com/smudge/nightshift"
readme = "README.md"
license = "MIT"

[dependencies]
objc = "0.2"
